# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: ê¹€ì˜ì‹
title: Student, Hallym University
email: krustm8@naver.com
# email_title: Email (Email title override)
website: http://34.64.239.164:8000
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Kazin7
facebook_username: kys.0814
instagram_username: los_ys_14

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/myPhoto2.jpg
about_content: | # this will include new lines to allow paragraphs
  - **í•™ë ¥**<br>
  ì„œìš¸ ì˜ë™ê³ ë“±í•™êµ(ì¡¸ì—…)<br>
  ì¶˜ì²œ í•œë¦¼ëŒ€í•™êµ(ì¬í•™)<br><br><br>
  - **ì†Œì†**<br>
  ì „ê³µ : ë¹…ë°ì´í„° <br>
  ë¶€ì „ê³µ : ì½˜í…ì¸  IOT <br><br><br>
  
  ì €ëŠ” ë°œì „í•´ë‚˜ê°€ëŠ” ê²ƒì„ ì¢‹ì•„í•˜ëŠ” ê³µëŒ€ìƒì…ë‹ˆë‹¤.<br>
  ì¢Œìš°ëª…ì€ **ì–´ì œì˜ ë‚˜ë³´ë‹¤ ì¡°ê¸ˆì€ ë‚˜ì•„ì§„ ë‚´ê°€ ë˜ì!** ì…ë‹ˆë‹¤.<br>
  í˜„ì¬ ê´€ì‹¬ìˆëŠ” ë¶„ì•¼ëŠ” **ë„¤íŠ¸ì›Œí¬**ì´ê³ , **ë³´ì•ˆ**ì—ë„ ê´€ì‹¬ì´ ìˆìŠµë‹ˆë‹¤.<br>
  
content:
  - title: âœí•™ìŠµ í”„ë¡œê·¸ë˜ë° ì–¸ì–´ # Title for the section
    layout: text # Type of content section (list/text)
    content:
      <h2>ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€1. java<br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€2. html/css<br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€3. C<br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€4. python<br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€5. R
      </h2><br>
     
  - title: ğŸ†ì·¨ë“ ìê²©ì¦
    layout: text # Type of content section (list/text)
    content:
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€<mark>ë„¤íŠ¸ì›Œí¬ê´€ë¦¬ì‚¬2ê¸‰</mark><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€<img src="images/Network.png"><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€<mark>ë¦¬ëˆ…ìŠ¤ë§ˆìŠ¤í„°2ê¸‰</mark><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€<img src="images/LinuxMaster.png"><br>
  - title: ğŸ“‹2022 2í•™ê¸° ì£¼ìš” ì»¤ë¦¬í˜ëŸ¼ ìˆ˜ê°• ì´ë ¥
    layout: text # Type of content section (list/text)
    content:
      <h2>ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€1. <mark>ë„¤íŠ¸ì›Œí¬ ë³´ì•ˆ</mark><br><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€2. <mark>ì„ í˜•ëŒ€ìˆ˜</mark><br><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€3. <mark>ì¸ê³µì§€ëŠ¥ì˜ì–´2</mark><br><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€4. <mark>ë¹…ë°ì´í„°ê¸°ì´ˆ</mark><br><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€5. <mark>VR/ARê²Œì„ì œì‘ê¸°ì´ˆ</mark><br><br>
                               ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€6. <mark>ì˜¤í”ˆì†ŒìŠ¤SWê°œë°œë„êµ¬í™œìš©</mark><br><br>
      </h2>
                                         
  - title: í”„ë¡œì íŠ¸ # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: WordPressë¥¼ ì´ìš©í•œ ì›¹ì‚¬ì´íŠ¸ êµ¬í˜„
        link: http://34.64.239.164:8000 (eg. sproogen.github.io/modern-resume-theme)(optional)
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
          
  - title: ì•ìœ¼ë¡œì˜ ê³„íš
    layout: text # Type of content section (list/text)
    content:
      <h2>                                     í˜„ì¬ëŠ” ë°±ì¤€ ì‚¬ì´íŠ¸ì—ì„œ ì½”ë”©í…ŒìŠ¤íŠ¸ ì¤€ë¹„ë¥¼ ìœ„í•œ ê³µë¶€ë¥¼ í•˜ê³ ìˆìœ¼ë©° ê³¨ë“œë¥¼ ì°ëŠ” ê²ƒì´ ëª©í‘œì…ë‹ˆë‹¤!<br>
                                     ë˜í•œ VMWAREë¥¼ ì‚¬ìš©í•œ ì„œë²„ë¥¼ êµ¬ë™í•˜ì—¬ ì„œë²„ì— ì¹¨íˆ¬í•˜ëŠ” ë„¤íŠ¸ì›Œí¬ ë³´ì•ˆì— ëŒ€í•˜ì—¬ ê³µë¶€í•  ê³„íšì…ë‹ˆë‹¤.<br>
                                     ìœ ë‹ˆí‹°ë¥¼ ì‚¬ìš©í•˜ì—¬ ê³µí¬ ê²Œì„ë„ ë§Œë“¤ ì˜ˆì •ì´ë©°, ì›¹ì‚¬ì´íŠ¸ë„ ë§Œë“¤ê²ƒì…ë‹ˆë‹¤!<br>
                                     ì»´í“¨í„° ì§€ì‹ë¿ë§Œì•„ë‹ˆë¼, ì œ ëª¸ë„ ì±™ê¸°ê¸° ìœ„í•´ ìš´ë™ë„ ê¾¸ì¤€íˆ í•  ì˜ˆì •ì…ë‹ˆë‹¤!<br>
      </h2>
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
