# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: ê¹€ì˜ì‹
title: Student, Hallym University
email: krustm8@naver.com
# email_title: Email (Email title override)
phone: 010-4925-9713
# phone_title: Phone (Phone title override)
website: http://34.64.239.164:8000
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Kazin7
facebook_username: kys.0814
instagram_username: los_ys_14

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/myPhoto2.jpg
about_content: | # this will include new lines to allow paragraphs
  - **í•™ë ¥**<br>
  ì„œìš¸ ì˜ë™ê³ ë“±í•™êµ<ì¡¸ì—…><br>
  ì¶˜ì²œ í•œë¦¼ëŒ€í•™êµ<ì¬í•™><br><br><br>
  - **ì†Œì†**<br>
  ì „ê³µ : ë¹…ë°ì´í„° <br>
  ë¶€ì „ê³µ : ì½˜í…ì¸  IOT <br>
content:
  - title: âœí•™ìŠµ í”„ë¡œê·¸ë˜ë° ì–¸ì–´ # Title for the section
    layout: text # Type of content section (list/text)
    content:
      <h2>ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€1. java<br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€2. java script / css<br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€3. C<br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€4. python<br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€5. R
      </h2><br>
     
  - title: ğŸ†ì·¨ë“ ìê²©ì¦
    layout: text # Type of content section (list/text)
    content:
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€<mark>ë„¤íŠ¸ì›Œí¬ê´€ë¦¬ì‚¬2ê¸‰</mark><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€<img src="images/Network.png"><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€<mark>ë¦¬ëˆ…ìŠ¤ë§ˆìŠ¤í„°2ê¸‰</mark><br>
      ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€ã€€<img src="images/LinuxMaster.png"><br>
  - title: ğŸ“‹2022 2í•™ê¸° ì£¼ìš” ì»¤ë¦¬í˜ëŸ¼ ìˆ˜ê°• ì´ë ¥
    layout: text # Type of content section (list/text)
    content:
    <table>
  <tr>
    <th>í•™ë…„</th>
    <th>í•™ê¸°</th>
    <th>êµ¬ë¶„</th>
    <th>ê³¼ëª©ëª…</th>
    <th>í•™ì </th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>ì „ê³µí•„ìˆ˜</th>
    <th>ìë°”í”„ë¡œê·¸ë˜ë°1</th>
    <th>3</th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>ì „ê³µí•„ìˆ˜</th>
    <th>ì´ì‚°êµ¬ì¡°ë¡ </th>
    <th>3</th>
  </tr>
  <tr>
    <th>1</th>
    <th>1</th>
    <th>ê¸°ì´ˆ - ì •ë³´</th>
    <th>ì»´í“¨íŒ…ì‚¬ê³ ì™€ ë¬¸ì œí•´ê²° - íŒŒì´ì¬</th>
    <th>2</th>
  </tr>
  <tr>
    <th>1</th>
    <th>2</th>
    <th>ì „ê³µí•„ìˆ˜</th>
    <th>ìë°”í”„ë¡œê·¸ë˜ë°2</th>
    <th>3</th>
  </tr>
  <tr>
    <th>1</th>
    <th>2</th>
    <th>ì „ê³µí•„ìˆ˜</th>
    <th>ì„ í˜•ëŒ€ìˆ˜</th>
    <th>3</th>
  </tr>
   <tr>
    <th>1</th>
    <th>2</th>
    <th>ê¸°ì´ˆ - ì •ë³´</th>
    <th>ì°½ì˜ì½”ë”© - ì›¹</th>
    <th>2</th>
  </tr>
  <tr>
    <th>2</th>
    <th>1</th>
    <th>ì „ê³µì„ íƒ</th>
    <th>ì†Œí”„íŠ¸ì›¨ì–´ê°œë¡ </th>
    <th>3</th>
  </tr>
  <tr>
    <th>2</th>
    <th>1</th>
    <th>ì „ê³µì„ íƒ</th>
    <th>ìë£Œêµ¬ì¡°</th>
    <th>3</th>
  </tr>
  <tr>
    <th>2</th>
    <th>1</th>
    <th>ì „ê³µì„ íƒ</th>
    <th>Cí”„ë¡œê·¸ë˜ë°</th>
    <th>3</th>
  </tr>
  <tr>
    <th>2</th>
    <th>1</th>
    <th>ì „ê³µì„ íƒ</th>
    <th>ë°ì´í„°ì‚¬ì´ì–¸ìŠ¤ê¸°ì´ˆ</th>
    <th>3</th>
  </tr>
  <tr>
    <th>2</th>
    <th>1</th>
    <th>ì „ê³µì„ íƒ</th>
    <th>ì†Œí”„íŠ¸ì›¨ì–´ ì„¸ë¯¸ë‚˜</th>
    <th>1</th>
  </tr>
</table>
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
