# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김영식
title: The College Student, Hallym University
email: krustm8@naver.com
# email_title: Email (Email title override)
website: http://34.64.239.164:8000
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Kazin7
facebook_username: kys.0814
instagram_username: los_ys_14

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/myPhoto2.jpg
about_content: | # this will include new lines to allow paragraphs
  - **학력**<br>
  서울 영동고등학교(졸업)<br>
  춘천 한림대학교(재학)<br><br><br>
  - **소속**<br>
  전공 : 빅데이터 <br>
  부전공 : 콘텐츠 IOT <br><br><br>
  
  저는 발전해나가는 것을 좋아하는 공대생입니다.<br>
  좌우명은 **어제의 나보다 조금은 나아진 내가 되자!** 입니다.<br>
  현재 관심있는 분야는 **네트워크**이고, **보안**에도 관심이 있습니다.<br>
  
content:
  - title: ✏학습 프로그래밍 언어 # Title for the section
    layout: text # Type of content section (list/text)
    content:
      <h2>　　　　　　　　　　　　　　　　　　　　　　　　　1. java<br>
      　　　　　　　　　　　　　　　　　　　　　　　　　2. html/css<br>
      　　　　　　　　　　　　　　　　　　　　　　　　　3. C<br>
      　　　　　　　　　　　　　　　　　　　　　　　　　4. python<br>
      　　　　　　　　　　　　　　　　　　　　　　　　　5. R
      </h2><br>
     
  - title: 🏆취득 자격증
    layout: text # Type of content section (list/text)
    content:
      　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　<mark>네트워크관리사2급</mark><br>
      　　　　　　　　　　　　　　　　　　<img src="images/Network.png"><br>
      　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　<mark>리눅스마스터2급</mark><br>
      　　　　　　　　　　　　　　　　　　<img src="images/LinuxMaster.png"><br>
  - title: 📋2022 2학기 주요 커리큘럼 수강 이력
    layout: text # Type of content section (list/text)
    content:
      <h2>　　　　　　　　　　　　　　　　　　　　　　　　　1. <mark>네트워크 보안</mark><br><br>
      　　　　　　　　　　　　　　　　　　　　　　　　　2. <mark>선형대수</mark><br><br>
      　　　　　　　　　　　　　　　　　　　　　　　　　3. <mark>인공지능영어2</mark><br><br>
      　　　　　　　　　　　　　　　　　　　　　　　　　4. <mark>빅데이터기초</mark><br><br>
      　　　　　　　　　　　　　　　　　　　　　　　　　5. <mark>VR/AR게임제작기초</mark><br><br>
                               　　　　　　　　　　　　　　　　　　　　　　　　　6. <mark>오픈소스SW개발도구활용</mark><br><br>
      </h2>
  - title: 📋현재까지 전공 관련 학점
    layout: text # Type of content section (list/text)
    content:
      <h2>　　　　　　　　　　　　　　　　　　　　　　　　　1. <mark>유헬스기초프로그래밍I = Ao</mark><br><br>
      　　　　　　　　　　　　　　　　　　　　　　　　　2. <mark>유헬스기초프로그래밍II = Ao</mark><br><br>
      　　　　　　　　　　　　　　　　　　　　　　　　　3. <mark>자바프로그래밍Ⅰ = Ao</mark><br><br>
      　　　　　　　　　　　　　　　　　　　　　　　　　4. <mark>자료구조 = A+</mark><br><br>
      　　　　　　　　　　　　　　　　　　　　　　　　　5. <mark>C프로그래밍I = A+</mark><br><br>
                               　　　　　　　　　　　　　　　　　　　　　　　　　6. <mark>	C++프로그래밍 = B+</mark><br><br>
                                                        　　　　　　　　　　　　　　　　　　　　　　　　　7. <mark>파이썬프로그래밍응용 = Ao</mark><br><br>
                                                        　　　　　　　　　　　　　　　　　　　　　　　　　8. <mark>오픈소스SW의이해 = Ao</mark><br><br>
                                                        　　　　　　　　　　　　　　　　　　　　　　　　　9. <mark>오픈소스리눅스실무 = Ao</mark><br><br>
                                                        　　　　　　　　　　　　　　　　　　　　　　　　　10. <mark>운영체제 = A+</mark><br><br>
                                                        　　　　　　　　　　　　　　　　　　　　　　　　　11. <mark>인공지능 = Ao</mark><br><br>
                                                        　　　　　　　　　　　　　　　　　　　　　　　　　12. <mark>웹프로그래밍 = A+</mark><br><br>
                                                        　　　　　　　　　　　　　　　　　　　　　　　　　13. <mark>윈도우프로그래밍 = A+</mark><br><br>
                                                        　　　　　　　　　　　　　　　　　　　　　　　　　14. <mark>데이터사이언스기초 = Ao</mark><br><br>
      </h2>
    
  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: WordPress를 이용한 <br>웹사이트 구현
        link: http://34.64.239.164:8000
        additional_links:
          - title:  무서운 게시판
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
                　　　　　　　　　　　　　　　　　　<img src="images/site.png"><br>
        description: | # this will include new lines to allow paragraphs
          Docker를 이용하여 Wordpress를 사용해보았습니다.
          GCP를 이용하여 서버를 구동하고 있고, 현재 서버를 운영중에 있습니다.
          <mark>무서운 이야기</mark>를 보고 싶다면 간단하게 와서 읽어보는 것을 추천합니다.
          
  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: R을 사용하여<br>그래프 그리기
        link: 
        additional_links:
          - title:  빅데이터 그래프
            icon: fab fa-github
            url: https://colab.research.google.com/drive/1v8-NocGZvtCyhZni_7Y0BY3IgqHphflR?usp=sharing
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://drive.google.com/file/d/1etLvlILV7yKz9f8N-19ItMncxszHVZ3P/view?usp=sharing
        quote: >
                　　　　　　　　　　　　　　　　　　<img src="images/table.png"><br>
                                  <img src="images/graph.png"><br>
        description: | # this will include new lines to allow paragraphs
          R을 사용하여 빅데이터를 정제하여 원하는 표본을 추출하여 그래프를 그렸습니다.<br>
          인터넷을 사용하는 고객의 정보를 담은 빅데이터를 남자,여자,계약기간을 기준으로 데이터를 추출하였고,<br>
          추출한 데이터를 ggplot2과 geombar를 사용하여 그래프를 그렸습니다.<br>
          <a href="https://drive.google.com/file/d/1etLvlILV7yKz9f8N-19ItMncxszHVZ3P/view?usp=sharing">데이터 링크</a><br>
          <a href="https://colab.research.google.com/drive/1v8-NocGZvtCyhZni_7Y0BY3IgqHphflR?usp=sharing">코드 파일 링크</a>
          
  - title: 현재 진행한 코딩 공부
  
    layout: text # Type of content section (list/text)
    content:
      <h2>                                     오라클 데이터베이스에 있는 기본 함수들과 객체, 그리고 권한같은 것들에 대해 공부했고,<br>
                                     자바로는 파일 입출력과 간단한 프로그래밍에 대해서 진행했습니다.<br>
                                     파이썬은 코딩 테스트에 유리하다고 생각하기 때문에 이 언어를 주로 사용하여 진행했습니다.<br>
                                     백준 사이트에서 동적 계산법까지 진행하였고,알고리즘은 dfs,bfs,다익스트라,프림,연결리스트 등등을 공부했습니다.<br>
      </h2>
      <a href="https://github.com/Kazin7/Coding-Study.git">Code Link</a>
  - title: 앞으로의 계획
    layout: text # Type of content section (list/text)
    content:
      <h2>                                     현재는 백준 사이트에서 코딩테스트 준비를 위한 공부를 하고있으며 골드를 찍는 것이 목표입니다!<br>
                                     또한 VMWARE를 사용한 서버를 구동하여 서버에 침투하는 네트워크 보안에 대하여 공부할 계획입니다.<br>
                                     유니티를 사용하여 공포 게임도 만들 예정이며, 웹사이트도 만들것입니다!<br>
                                     컴퓨터 지식뿐만아니라, 제 몸도 챙기기 위해 운동도 꾸준히 할 예정입니다!<br>
      </h2>
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
